spring:
  profiles:
    active:
    - dev
---
server: 8001
spring:
   profiles: dev
   application:
    name: microservicecloud-config-dept-client
   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型(此处无法通过？)
    type: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.panda.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka:
  client: #
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true  # 访问路径可以有ip地址

info:
  app.name: panda-microservicecloud-springcloudconfig01
  company.name: www.panda.com
  build.artifactId: $project.artifactId$   # unfinished 实际配置了，但是却取不出来
  build.version: $project.version$          # unfinished 实际配置了，但是却取不出来